In [1]:
print("Hello world")

Hello world


In [3]:
import numpy as np

In [11]:
x = np.array([1, 2, 3, 4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
y= [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


# array

In [2]:
import numpy as np

x = [1,2,3,4]
y= np.array([1,2,3,4,5])

print(type(x))
print(type(y))



<class 'list'>
<class 'numpy.ndarray'>


In [5]:
l =[]

for i in range (1,5):
    int_1 = int(input("enter: "))
    l.append(int_1)
    
print(np.array(1))


enter: 12
enter: 13
enter: 14
enter: 15
1


In [8]:
l =[]

for i in range (1,5):
    int_1 = int(input("Enter: "))
    l.append(int_1)
    
print(np.array(l))


Enter: 12
Enter: 13
Enter: 14
Enter: 15
[12 13 14 15]


# zeroes


In [4]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))


print(ar_zero)
print(ar_zero1)


[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [6]:
ar_one = np.ones(4)

print(ar_one)

[1. 1. 1. 1.]


# Empty array

In [7]:
ar_emp = np.empty(4)

print(ar_emp)

[1. 1. 1. 1.]


# Range

In [8]:
ar_rn = np.arange(4)

print(ar_rn)

[0 1 2 3]


# Diagonal

In [13]:
ar_dia = np.eye(3)

print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
ar_dia1 = np.eye(3,5)

print(ar_dia1)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# linspace

In [16]:
ar_lin = np.linspace(0,10,num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


# Random 

# Rand()

In [21]:
a = np.random.rand(5)
print(a)
# [0.47246412 0.46394876 0.93116619 0.30417678 0.20906732]

[0.42890926 0.34810006 0.71603995 0.07747409 0.2643208 ]


In [19]:
b = np.random.rand(2,5)
print(b)

[[0.91880688 0.19256613 0.60985214 0.72650645 0.61464901]
 [0.23951277 0.13290313 0.38413489 0.95593264 0.1383898 ]]


# Ranf()

In [22]:
c = np.random.ranf(5)
print(c)

[0.34278409 0.90817168 0.75127325 0.58313491 0.08076725]


# randn()

In [23]:
d = np.random.randn(4)
print(d)

[-1.07743045 -0.69885169  0.08126594  0.65785716]


# randint()

In [24]:
e = np.random.randint(5,20,5)
# e = np.random.randint(min,max,total_values)
print(e)

[13  9  8  8  7]


# Datatype

In [26]:
var = np.array([1,2,3,4,12,13,14])
print("Datatype: ",var.dtype)

Datatype:  int32


In [28]:
var1 = np.array([1.0,2.0,3.3,4.4])
print("Datatype: ",var1.dtype)

Datatype:  float64


In [29]:
var2 = np.array(["a","b","c"])
print("Datatype: ",var2.dtype)

Datatype:  <U1


In [32]:
x = np.array([1,2,3,4],dtype = np.int8)

print("Datatype: ",x.dtype)
print(x)

Datatype:  int8
[1 2 3 4]


In [33]:
x1 = np.array([1,2,3,4],dtype = "f")

print("Datatype: ",x1.dtype)
print(x1)

Datatype:  float32
[1. 2. 3. 4.]


In [35]:
x2 = np.array([1,2,3,4])
new = np.float32(x2)
new_one = np.int_(new)

print("Datatype: ",x2.dtype)
print("Datatype: ",new.dtype)
print("Datatype: ",new_one.dtype)
print(x2)
print(new)
print(new_one)

Datatype:  int32
Datatype:  float32
Datatype:  int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [36]:
x3 = np.array([1,2,3,4])

new_1 = x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


# Arithmetic Operation

# add

In [37]:
var = np.array([1,2,3,4])
varadd = var + 3

print(varadd)

[4 5 6 7]


In [38]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1 + var2

print(varadd)

[2 4 6 8]


In [43]:
# Add function in numpy
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = np.add(var1,var2)

print(varadd)

[2 4 6 8]


In [39]:
var = np.array([1,2,3,4])
var2 = var - 3

print(var2)

[-2 -1  0  1]


In [45]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varsub = np.subtract(var1,var2)

print(varsub)

[0 0 0 0]


In [40]:
var = np.array([1,2,3,4])
var2 = var * 3

print(var2)

[ 3  6  9 12]


In [41]:
var = np.array([1,2,3,4])
var2 = var / 3

print(var2)

[0.33333333 0.66666667 1.         1.33333333]


In [46]:
var = np.array([1,2,3,4])
var2 = var % 3

print(var2)

[1 2 0 1]


# 2d Array

In [49]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])
print(var21)
print()
print(var22)
print()
varadd = var21 + var22

print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [50]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])
print(var21)
print()
print(var22)
print()
varadd = np.add(var21,var22)

print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [51]:
var = np.array([1,2,3,4])
var2 = np.reciprocal(var)

print(var2)

[1 0 0 0]


# Arithmetic function

In [53]:
var = np.array([1,2,3,4,5,3,2])
print("Minimum number: ",np.min(var))
print("Max number: ",np.max(var))

Minimum number:  1
Max number:  5


In [59]:
var = np.array([1,2,3,4,5,3,2])
print("Minimum number: ",np.min(var),"Position of the min:",np.argmin(var))
print("Max number: ",np.max(var),"Position of the max:",np.argmax(var))
print("sqrt:",np.sqrt(var))

Minimum number:  1 Position of the min: 0
Max number:  5 Position of the max: 4
sqrt: [1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 1.41421356]


In [58]:
var = np.array([[1,2,3],[9,7,5]])

print(np.min(var,axis=0))


[1 2 3]


In [62]:
var2 = np.array([1,2,3])

print("Sine:",np.sin(var2))
print("Cos:",np.cos(var2))
print("Cumsum",np.cumsum(var2))


Sine: [0.84147098 0.90929743 0.14112001]
Cos: [ 0.54030231 -0.41614684 -0.9899925 ]
Cumsum [1 3 6]


# Shape

In [65]:
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [68]:
var1 = np.array([1,2,3,4],ndmin=4)
print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


# Reshape

In [71]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)
print()

x =var2.reshape(3,2)

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [74]:
var1 = np.array([1,2,3])
print(var1.shape)
print()
print(var1)

var2 =np.array([[1],[2],[3]])
print(var2)
print()
print(var2.shape)
print()

print(var1+var2)

(3,)

[1 2 3]
[[1]
 [2]
 [3]]

(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
